INSERT INTO TODO(ID, NAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES(1121, 'Samirul', 'I AM SUCCESSFULL', CURRENT_DATE(), TRUE);

INSERT INTO TODO(ID, NAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES(1128, 'Samirul', 'I AM THE BEST', CURRENT_DATE(), TRUE);

INSERT INTO TODO(ID, NAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES(11255, 'SAMIRUL', 'I AM GOING WELL', CURRENT_DATE(), TRUE);